# -----------------------------------------------------------------
# Configuration file for http://travis-ci.org/#!/karmi/tire-contrib
# -----------------------------------------------------------------

language: ruby

rvm:
  - 1.9.3

script: "bundle exec rake test"

services:
  - elasticsearch

notifications:
  disable: true
